// <auto-generated />
namespace Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_Ids_to_AgeRestriction_class_and_MoviePosition_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Ids_to_AgeRestriction_class_and_MoviePosition_class));
        
        string IMigrationMetadata.Id
        {
            get { return "201710291048191_Added_Ids_to_AgeRestriction_class_and_MoviePosition_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
