// <auto-generated />
namespace Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_MovieTitle_and_MovieDuration_to_MoviePosition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_MovieTitle_and_MovieDuration_to_MoviePosition));
        
        string IMigrationMetadata.Id
        {
            get { return "201711171655184_Added_MovieTitle_and_MovieDuration_to_MoviePosition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
