// <auto-generated />
namespace Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_EnglishName_To_AgeRestriction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_EnglishName_To_AgeRestriction));
        
        string IMigrationMetadata.Id
        {
            get { return "201712311133270_Added_EnglishName_To_AgeRestriction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
