// <auto-generated />
namespace Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_MovieType_to_MoviePositionDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_MovieType_to_MoviePositionDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201712152031297_added_MovieType_to_MoviePositionDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
